### PR TITLE
porting to NXF DSL2

### PR DESCRIPTION
**Pull request by ggabernet**
Many thanks for contributing to nf-core/bcellmagic!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/bcellmagic branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/bcellmagic)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/bcellmagic/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by ggabernet** [comment]
Hi @phue any reason why you closed this PR?

**Comment by ggabernet** [comment]
ah ok fine then 👍  yeah I wanna have it ported in the next couple of weeks

**Comment by phue** [comment]
@ggabernet Apologies, I didn't even realize I closed it. Was a mistake indeed.

**Comment by ggabernet** [comment]
> @ggabernet Apologies, I didn't even realize I closed it. Was a mistake indeed.

sure, no worries!

**Comment by ggabernet** [comment]
Just waiting for the next tools release and the first port to DSL2 should be ready

**Comment by ggabernet** [comment]
The nf-core lint tests are failing because I updated the `Nfcoreschema.groovy` for the new Memory and time resources regexes. This will be added to the next nf-core tools release.

**Comment by ggabernet** [comment]
I will merge this to `dsl2` so collaborators can contribute and we will do the usual reviews when we merge to the `dev` branch 😄

**Pull request merged**
